### ISSUE TITLE
Consume secrets from KeyVault using Managed Identity (MSI)

### ISSUE THREAD

**Issue by arani87** [Azure/azure-microprofile#1]
Currently, the connection is authenticated with SPN. Which is not super secure per se.
This should also be possible using MSI

**Comment by majguo** [comment]
It's fixed in https://github.com/Azure/azure-microprofile/releases/tag/1.0.0-beta.1, and the artifacts are published to [Maven Central: com.azure.microprofile (sonatype.com)](https://central.sonatype.com/namespace/com.azure.microprofile).
